"""Add watchlist and trade journal tables

Revision ID: 9e3467a171a1
Revises: f7fadf0309ac
Create Date: 2026-05-02 22:51:16.718743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3467a171a1'
down_revision: Union[str, Sequence[str], None] = 'f7fadf0309ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
