"""Add watchlist and trade journal

Revision ID: c86bf5be9dd0
Revises: 0e914ba819f4
Create Date: 2026-05-02 23:03:04.839398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86bf5be9dd0'
down_revision: Union[str, Sequence[str], None] = '0e914ba819f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
