"""Initial schema - create all tables (trades, predictions, backtest_results, news_articles, fiidii_flows, user_preferences)

Revision ID: f7fadf0309ac
Revises: 
Create Date: 2026-04-14 21:44:29.470706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7fadf0309ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('total_return_pct', sa.Float(), nullable=True),
    sa.Column('buy_hold_return_pct', sa.Float(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('win_rate_pct', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_created_at'), 'backtest_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtest_results_id'), 'backtest_results', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_results_strategy'), 'backtest_results', ['strategy'], unique=False)
    op.create_index(op.f('ix_backtest_results_symbol'), 'backtest_results', ['symbol'], unique=False)
    op.create_table('fiidii_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('fii_gross_buy', sa.Float(), nullable=True),
    sa.Column('fii_gross_sell', sa.Float(), nullable=True),
    sa.Column('fii_net', sa.Float(), nullable=True),
    sa.Column('dii_gross_buy', sa.Float(), nullable=True),
    sa.Column('dii_gross_sell', sa.Float(), nullable=True),
    sa.Column('dii_net', sa.Float(), nullable=True),
    sa.Column('combined_net', sa.Float(), nullable=True),
    sa.Column('signal', sa.String(length=50), nullable=True),
    sa.Column('pressure_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiidii_flows_created_at'), 'fiidii_flows', ['created_at'], unique=False)
    op.create_index(op.f('ix_fiidii_flows_date'), 'fiidii_flows', ['date'], unique=False)
    op.create_index(op.f('ix_fiidii_flows_dii_net'), 'fiidii_flows', ['dii_net'], unique=False)
    op.create_index(op.f('ix_fiidii_flows_fii_net'), 'fiidii_flows', ['fii_net'], unique=False)
    op.create_index(op.f('ix_fiidii_flows_id'), 'fiidii_flows', ['id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('is_market_news', sa.Boolean(), nullable=True),
    sa.Column('is_rbi_news', sa.Boolean(), nullable=True),
    sa.Column('is_earnings_news', sa.Boolean(), nullable=True),
    sa.Column('market_impact', sa.String(length=20), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_url'), 'news_articles', ['url'], unique=True)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('signal', sa.Enum('BUY', 'SELL', 'HOLD', name='tradesignal'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('prediction_date', sa.DateTime(), nullable=True),
    sa.Column('top_feature_1', sa.String(length=100), nullable=True),
    sa.Column('top_feature_1_contribution', sa.Float(), nullable=True),
    sa.Column('top_feature_2', sa.String(length=100), nullable=True),
    sa.Column('top_feature_2_contribution', sa.Float(), nullable=True),
    sa.Column('top_feature_3', sa.String(length=100), nullable=True),
    sa.Column('top_feature_3_contribution', sa.Float(), nullable=True),
    sa.Column('actual_signal', sa.Enum('BUY', 'SELL', 'HOLD', name='tradesignal'), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_date'), 'predictions', ['prediction_date'], unique=False)
    op.create_index(op.f('ix_predictions_symbol'), 'predictions', ['symbol'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('signal', sa.Enum('BUY', 'SELL', 'HOLD', name='tradesignal'), nullable=True),
    sa.Column('ml_confidence', sa.Float(), nullable=True),
    sa.Column('grade', sa.Enum('A', 'B', 'C', 'D', 'F', name='tradegrade'), nullable=True),
    sa.Column('risk_pct', sa.Float(), nullable=True),
    sa.Column('reward_pct', sa.Float(), nullable=True),
    sa.Column('rr_ratio', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_created_at'), 'trades', ['created_at'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('default_symbol', sa.String(length=20), nullable=True),
    sa.Column('default_risk_pct', sa.Float(), nullable=True),
    sa.Column('default_capital', sa.Float(), nullable=True),
    sa.Column('notify_strong_signals', sa.Boolean(), nullable=True),
    sa.Column('notify_market_mood_change', sa.Boolean(), nullable=True),
    sa.Column('notify_high_impact_news', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_created_at'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_predictions_symbol'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_prediction_date'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_news_articles_url'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_fiidii_flows_id'), table_name='fiidii_flows')
    op.drop_index(op.f('ix_fiidii_flows_fii_net'), table_name='fiidii_flows')
    op.drop_index(op.f('ix_fiidii_flows_dii_net'), table_name='fiidii_flows')
    op.drop_index(op.f('ix_fiidii_flows_date'), table_name='fiidii_flows')
    op.drop_index(op.f('ix_fiidii_flows_created_at'), table_name='fiidii_flows')
    op.drop_table('fiidii_flows')
    op.drop_index(op.f('ix_backtest_results_symbol'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_strategy'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_id'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_created_at'), table_name='backtest_results')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
